package exercicios.exercicio33.lutadores;

/*
 * @author Luiz Carlos Dinani
 */
public class TelaLutadores extends javax.swing.JFrame {

    /**
     * Creates new form TelaLutadores
     */
    public TelaLutadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barP1 = new javax.swing.JProgressBar();
        barP2 = new javax.swing.JProgressBar();
        lblVS = new javax.swing.JLabel();
        btnApanharP1 = new javax.swing.JButton();
        btnApanharP2 = new javax.swing.JButton();
        btnConcentrarP1 = new javax.swing.JButton();
        btnConcentrarP2 = new javax.swing.JButton();
        lblDerrotaP1 = new javax.swing.JLabel();
        lblDerrotaP2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barP1.setValue(100);

        barP2.setValue(100);

        lblVS.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVS.setText("VS");

        btnApanharP1.setText("Apanhar");
        btnApanharP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApanharP1ActionPerformed(evt);
            }
        });

        btnApanharP2.setText("Apanhar");
        btnApanharP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApanharP2ActionPerformed(evt);
            }
        });

        btnConcentrarP1.setText("Concentrar Força");
        btnConcentrarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcentrarP1ActionPerformed(evt);
            }
        });

        btnConcentrarP2.setText("Concentrar Força");
        btnConcentrarP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcentrarP2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApanharP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnApanharP2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConcentrarP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConcentrarP2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(barP1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(lblVS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDerrotaP1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDerrotaP2)
                            .addComponent(barP2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDerrotaP1)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDerrotaP2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApanharP1)
                    .addComponent(btnApanharP2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnConcentrarP1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnConcentrarP2)))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Lutador lutador1 = new Lutador();
    Lutador lutador2 = new Lutador();
    
    private void btnApanharP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApanharP1ActionPerformed
        if(lutador1.getVida()>0 && lutador2.getVida()>0){
            lutador1.apanhar();
            barP1.setValue(lutador1.getVida());        
        }else if(lutador1.getVida()<=0){
            lblDerrotaP1.setText("Jogador 1 Perdeu");
        }
    }//GEN-LAST:event_btnApanharP1ActionPerformed

    private void btnConcentrarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcentrarP1ActionPerformed
        if(lutador1.getVida()>0 && lutador2.getVida()>0){
            lutador1.concentrarForca();
            barP1.setValue(lutador1.getVida());        
        }else if(lutador1.getVida()<=0){
            lblDerrotaP1.setText("Jogador 1 Perdeu");
        }
    }//GEN-LAST:event_btnConcentrarP1ActionPerformed

    private void btnApanharP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApanharP2ActionPerformed
        if(lutador1.getVida()>0 && lutador2.getVida()>0){
            lutador2.apanhar();
            barP2.setValue(lutador2.getVida());        
        }else if(lutador2.getVida()<=0){
            lblDerrotaP2.setText("Jogador 2 Perdeu");
        }
    }//GEN-LAST:event_btnApanharP2ActionPerformed

    private void btnConcentrarP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcentrarP2ActionPerformed
        if(lutador1.getVida()>0 && lutador2.getVida()>0){
            lutador2.concentrarForca();
            barP2.setValue(lutador2.getVida());        
        }else if(lutador2.getVida()<=0){
            lblDerrotaP2.setText("Jogador 2 Perdeu");
        }
    }//GEN-LAST:event_btnConcentrarP2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLutadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barP1;
    private javax.swing.JProgressBar barP2;
    private javax.swing.JButton btnApanharP1;
    private javax.swing.JButton btnApanharP2;
    private javax.swing.JButton btnConcentrarP1;
    private javax.swing.JButton btnConcentrarP2;
    private javax.swing.JLabel lblDerrotaP1;
    private javax.swing.JLabel lblDerrotaP2;
    private javax.swing.JLabel lblVS;
    // End of variables declaration//GEN-END:variables
}
